import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../assets/globals.css'
import NavbarWeb from '@/components/NavbarWeb'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className="min-h-screen bg-background font-sans antialiased">
        <NavbarWeb />
        {children}
      </body>
    </html>
  )
}
